services:
  - type: web
    name: phone-book-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}